CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS test (
    id serial PRIMARY KEY,
    pw text
);

CREATE OR REPLACE FUNCTION auth ()
    RETURNS jwt
    AS $$
BEGIN
    RETURN ('me',
        12,
        'ben')::jwt;
END;
$$
LANGUAGE plpgsql
SECURITY DEFINER;

CREATE FUNCTION addUser (usrname text, pswd text)
    RETURNS jwt
    AS $$
DECLARE
    salt text = gen_salt('bf');
    passwd text = crypt(pswd, salt);
BEGIN
    INSERT INTO users (username, pass, salt)
    VALUES (usrname, passwd, salt);
    RETURN ('new',
        12,
        usrname)::jwt;
END;
$$
LANGUAGE plpgsql
VOLATILE;

SELECT
    *
FROM
    users;

